--ozone-platform=wayland
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WaylandLinuxDrmSyncobj
--use-gl=egl
--enable-gpu-rasterization
--enable-accelerated-2d-canvas
--ignore-gpu-blocklist
--disable-webgpu
--disable-gpu-sandbox
